# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache YARN dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      # Runs a single command using the runners shell
      - name: install
        run: yarn --no-progress --non-interactive --frozen-lockfile

      # Runs a single command using the runners shell
      - name: lint
        run: npm run lint

      # Runs a single command using the runners shell
      - name: format
        run: npm run format

      # Runs a single command using the runners shell
      - name: compile
        run: npx hardhat compile

      # Runs a single command using the runners shell
      - name: test
        run: npx hardhat test

      # Runs a single command using the runners shell
      - name: coverage
        run: npx hardhat coverage
